### ISSUE TITLE
Update `org.bouncycastle:bcprov-jdk15on` dependency

### ISSUE THREAD

**Issue by kackogut** [ajamaica/Solana.kt#124]
HI! Since our project uses your library and both [web3j](https://github.com/web3j/web3j) and [Wallet Connect V2](https://github.com/WalletConnect/WalletConnectKotlinV2) when building the project we are getting errors connected with unsupported `Bouncy Castle` versions:
```
Caused by: com.android.builder.merge.DuplicateRelativeFileException: 2 files found with path 'org/bouncycastle/x509/CertPathReviewerMessages_de.properties'.
```

Everything is working fine when I exclude `Bouncy Castle` from Solana library
```
    implementation("com.github.metaplex-foundation:SolanaKT:2.0.1") {
        exclude(group = "org.bouncycastle", module = "bcprov-jdk15to18")
    }
```

But since both `web3j` and `Wallet Connect` uses the same version of `org.bouncycastle` which is `1.7.0` it will also be possible to update it in the `SolanaKT` library from `1.6.8` to `1.7.0`

**Comment by ajamaica** [comment]
I will take a look at it

**Comment by ajamaica** [comment]
It will be update it to 1.72 since it depends on bitcoin core.

**Comment by kackogut** [comment]
Thank you!

**Comment by ajamaica** [comment]
This was a simple one. Thanks for filling the issue. Anything else feel free to fill an issue

**Comment by ajamaica** [comment]
We are ready for a new release.
