### ISSUE TITLE
Give the option to use the localhost

### ISSUE THREAD

**Issue by dbaroncelli** [ajamaica/Solana.kt#59]
currently, it's possible to use only with predefined networks:
mainnet-beta
devnet
testnet

I wasn't able to make it work with:
http://localhost:8899

**Comment by ajamaica** [comment]
You can pass the URL on a custom network https://github.com/ajamaica/Solana.kt/blob/1a79932e67e698f2dba5f347fb74dd47d702f8fb/solana/src/main/java/com/solana/networking/RPCEndpoint.kt
