### ISSUE TITLE
Feature request: Make Account() additionally generate mnemonic

### ISSUE THREAD

**Issue by samdowd** [ajamaica/Solana.kt#62]
Currently Account() returns a keypair with publicKey and privateKey. There's already support for reading accounts from mnemonics, should be relatively easy to generate a mnemonic instead.

**Comment by ajamaica** [comment]
Generate mnemonic from a publicKey and privateKey? Can you give detail of what you are trying to do?

**Comment by samdowd** [comment]
Generate mnemonic *in addition to* a publicKey and privateKey.

I'm trying to generate an account for the first time. And I want a mnemonic included on that account object. I believe this is already how it works in the Swift library. But in the Kotlin library, it only gives me the public and private key. Which can't be reversed into the mnemonic, so the mnemonic is lost forever. I've found a workaround by generating my own mnemonic using a different library then feeding that mnemonic into Solana.kt to create an account, but this seems like something the SDK should do automatically (as in the Swift SDK).

**Comment by dreamchaser96** [comment]
> Generate mnemonic _in addition to_ a publicKey and privateKey.
> 
> I'm trying to generate an account for the first time. And I want a mnemonic included on that account object. I believe this is already how it works in the Swift library. But in the Kotlin library, it only gives me the public and private key. Which can't be reversed into the mnemonic, so the mnemonic is lost forever. I've found a workaround by generating my own mnemonic using a different library then feeding that mnemonic into Solana.kt to create an account, but this seems like something the SDK should do automatically (as in the Swift SDK).

Any update on this?

**Comment by ajamaica** [comment]
This now implemented using bip39 and you can use HotWallet.FromMnemonic
