### ISSUE TITLE
How to get transaction information from getConfirmedTransaction?

### ISSUE THREAD

**Issue by swiftyLuke** [ajamaica/Solana.kt#64]
Hello,

I am trying to fetch transaction history and it is successful but the result is mapped to object which doesn't contain transaction-specific information. On Solana swift I can get it from ConfirmedTransaction.Instruction object, but in Kotlin there are only three fields available:
![Zrzut ekranu 2022-02-21 o 13 53 26](https://user-images.githubusercontent.com/92109995/154959004-2d25af2e-7cd2-4e43-93ea-f1896f7d76fc.png)

Any chance to get an update here? 

Thanks in advance!

**Comment by kaushal-inexture** [comment]
Hello swiftyLuke,

Can I know how you are getting account? Using Solana

**Comment by ajamaica** [comment]
This is now fixed on https://github.com/metaplex-foundation/SolanaKT/pull/107
