### ISSUE TITLE
MinSdk should be lower than 30

### ISSUE THREAD

**Issue by creativedrewy** [ajamaica/Solana.kt#79]
Is there any reason why MinSdk is 30? That is pretty limiting for the Android device landscape. Is there any reason it needs to be that high? MinSdk 21-24 would be much more ideal for a library such as this.

**Comment by ajamaica** [comment]
The Base58 lib only. This is  a valid concern i haven't look at it.

**Comment by ajamaica** [comment]
BTW min version is 27 target is 30
