### ISSUE TITLE
Feature Request: Partial Signing Transactions

### ISSUE THREAD

**Issue by samdowd** [ajamaica/Solana.kt#84]
In line with Solana.swift, I'd like the ability to partially sign transactions. I'm trying to partially sign the transaction on the device with a remote fee payer (see my PR: https://github.com/ajamaica/Solana.kt/pull/83) then send the partially signed transaction to a JS server that will sign the transaction as the fee payer and submit it.

**Comment by samdowd** [comment]
My PR only added the ability to set FeePayer, not to partially sign transactions. This library is still missing:
1. `Transaction.partialSign`, [JS implementation](https://github.com/solana-labs/solana-web3.js/blob/13cd6f5/src/transaction.ts#L494), [Swift implementation](https://github.com/ajamaica/Solana.Swift/blob/master/Sources/Solana/Models/SendingTransaction/Transaction.swift#L76)
2. `Transaction.serialize` options to `requireAllSignatures` and `verifySignatures`, [JS implementation](https://github.com/solana-labs/solana-web3.js/blob/13cd6f5/src/transaction.ts#L62)

And other updates I'm sure, but this is what I can see with my Solana understanding.

**Comment by ajamaica** [comment]
Lets add ticket for each
