### ISSUE TITLE
Feature Request: Change name to work with Jitpack

### ISSUE THREAD

**Issue by samdowd** [ajamaica/Solana.kt#85]
Currently the library cannot be pulled from Jitpack because of the "." in Solana.kt. I've tested on my fork changing the name to SolanaKT and it fixed the issue, so I propose doing that here.

**Comment by ajamaica** [comment]
This is why!. I did not know this was an issue.

**Comment by ajamaica** [comment]
Solana.kt repo right?

**Comment by ajamaica** [comment]
I will change the repo name.

**Comment by ajamaica** [comment]
Done

**Comment by samdowd** [comment]
Yeah I looked at the Jitpack logs and it was putting the resources in one directory and then looking for them in another. Thanks!
