### ISSUE TITLE
sendSPLTokens throws NullPointerException

### ISSUE THREAD

**Issue by MountainNine** [ajamaica/Solana.kt#90]
I need to send SPL Token with android, so I'm researching this library.

When I tested sendSPLTokens, it throws NullPointerException.

I debugged the code, then sendSPLTokens -> fingSPLTokenDestinationAddress -> getAccountInfo with createProgramAddress throws the error.

Also, I explored your Solana.Swift code, and I found that there are [some commits about findSPLTokenDestinationAddress](https://github.com/ajamaica/Solana.Swift/commit/6d7dcb575419d054f33ec7b8e1780a9f58a97a6e)

Is it related to this issue?

**Comment by ajamaica** [comment]
Yes. this needs to get fixed ASAP. Sorry for the delay reply

**Comment by kambaroff** [comment]
Hello, is this fix in the release? Because it still throws nullPointerException. Using 1.1.15 version.
