### ISSUE TITLE
Seed Phrase Generate Issue

### ISSUE THREAD

**Issue by nikunjinexture** [ajamaica/Solana.kt#95]
@ajamaica I am using this library for Android Solana wallet and generating the Seed phrase for create the account, but getting 48 words of seed phrase while generate the phrase. Where In the [iOS Solana](https://github.com/ajamaica/Solana.Swift) and Web generated 24 words of seed phrase. So not able to Restore Existing Wallet in the [Solana](https://www.sollet.io). Can you please guide us where need to change?

**Comment by ajamaica** [comment]
There was no Mnemonic bip39 generation. That PR will add this functionality.
